<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_CustomizeCABAV
 * @author     Extension Team
 * @copyright  Copyright (c) 2021 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
// @codingStandardsIgnoreFile
use \Bss\CustomizeCABAV\Block\Widget\AlsoViewed;
?>
<?php
/**
 * @var AlsoViewed $block
 */
?>
<?php if ($block->isEnable()) : ?>
    <?php
        $displayMode = $block->getData('display') == AlsoViewed::MODE_SLIDER ? "slider" : "grid";
        $displayItem = 5;
        if ($block->getData('number_product')) {
            $displayItem = (int) $block->getData('number_product');
        }
    ?>
    <style>
        @media (min-width: 240px) {
            .page-layout-1column .grid.block.widget .alsoview-list .products-grid .product-item
            {
                width: 100% !important;
            }
        }
        @media (min-width: 600px) {
            .page-layout-1column .grid.block.widget .alsoview-list .products-grid .product-item
            {
                width: calc(100% / 3) !important;
            }
        }
        @media (min-width: 1024px) {
            .page-layout-1column .grid.block.widget .alsoview-list .products-grid .product-item
            {
                width: calc(100% / <?= /** @noEscape */ $displayItem ?>) !important;
            }
        }
    </style>
    <div class="widget block block-static-block <?= /** @noEscape */ $displayMode ?>">
        <?php $currentProduct = $block->getCurrentProduct(); ?>
        <?php if ($currentProduct): ?>
            <div class="alsoview-list"
                 data-mage-init='{
                "Bss_CABAV/js/alsoboughtview": {
                    "url": "<?php echo $block->getUrl('viewed/alsoview/product', ['_secure' => true]) ?>",
                    "data": <?php echo $block->getDataJson() ?>,
                    "type": "alsoview",
                    "urlsave": "<?php echo $block->getUrl('viewed/alsoview/save', ['_secure' => true]) ?>",
                    "currentproduct": "<?php echo $currentProduct['product_id'] ?>"
                }
            }'></div>
        <?php else: ?>
            <div class="alsoview-list"
                 data-mage-init='{
                "Bss_CABAV/js/alsoboughtview": {
                    "url": "<?php echo $block->getUrl('viewed/alsoview/product', ['_secure' => true]) ?>",
                    "data": <?php echo $block->getDataJson() ?>,
                    "type": "alsoview",
                    "urlsave": "",
                    "currentproduct": ""
                }
            }'></div>
        <?php endif; ?>
    </div>
<?php endif; ?>
