<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_FBT
 * @author     Extension Team
 * @copyright  Copyright (c) 2017-2018 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>
<?php
$helper = $this->helper('Bss\FBT\Helper\Data');
$imageHelper = $this->helper('Magento\Catalog\Helper\Image');
$product = $block->getProduct();
$errormessageCart = $block->getErrorMessageCart();
$type_add = $block->getTypeadd();
$product_success = isset($product['success'])? $product['success'] : null;
$product_fail = isset($product['errors'])? $product['errors'] : null;
$cart = $block->getCart();
$priceIncludesTax = $block->priceIncludesTax();
?>
<div class="popup">
    <div class="header">
        <span><?php echo __('Shopping Cart'); ?></span>
    </div>
    <?php if ($errormessageCart): ?>
        <p class="message error">
            <?php echo $errormessageCart; ?>
        </p>
    <?php else: ?>
        <?php if ($block->getTypeadd() == 'single' && !$product_fail ): ?>
            <p class="message">
                <?php echo __('You added '); ?>

                <a href="<?php echo $product->getProductUrl() ?>" title="<?php echo $product->getName(); ?>">
                    <?php echo $product->getName();?>
                </a>
                <?php echo $block->getRelatedAdded() ? __(' and related products') : ''; ?>
                <?php echo __(' to your shopping cart'); ?>
            </p>
        <?php endif ?>
        <?php if ($block->getTypeadd() == 'muntiple' && $product_success): ?>
            <p class="message"><span><?php echo __('You have added the following items to the cart: '); ?></span></p>
            <div class="product-image">
                <div id="product-slider" class="owl-carousel owl-theme content-slider">
                    <?php foreach ($product_success as  $productss): ?>
                        <?php $products = $block->loadProductId($productss['id']);

                        ?>
                        <div  class="item product-info">
                            <div class="product-image-aj">
                                <img  class="" src="<?php echo $imageHelper->init($products, 'category_page_list', ['height' => 100 , 'width'=> 100])->getUrl();?>">
                            </div>
                            <a href="<?php echo $products->getProductUrl() ?>" title="<?php echo $products->getName(); ?>">
                                <span><?php echo $products->getName();?></span>
                            </a>
                            <?php if($helper->isPShowprice()) :?>
                                <span><?php echo $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($productss['price'], true, false);?></span>
                            <?php endif; ?>
                        </div>
                    <?php endforeach ?>
                </div>
            </div>
        <?php endif; ?>
        <?php if ($block->getTypeadd() == 'single' && !$product_fail): ?>
            <div class="product-image">
                <img src="<?php echo $imageHelper->init($product, 'category_page_list', ['height' => 100 , 'width'=> 100])->getUrl();?>">
                <?php if($helper->isPShowprice()) :?>
                    <div>
                        <span><?php echo $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($product->getFinalPrice(), true, false);?></span>
                    </div>
                <?php endif; ?>
            </div>
        <?php endif ?>
    <?php endif ?>
    <?php if ($product_fail): ?>
        <form action="<?= $block->getUrl('fbt/cart/addMultiple')?>" method="post" id="product_fbt_form_popup" data-mage-init='{"validation":{}}'>
            <div class="product-info-er">
                <?php $i = 1 ;foreach ($product_fail as $productId => $data): ?>
                    <?php $_product = $block->loadProductId($productId); ?>
                    <div class="item-er-pu">
                        <p class="messages-error">
                            <span ><?php echo $data['mess'] ?></span>
                        </p>
                        <div class="item-info-er">
                            <div class="item-img-er">
                                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image-<?php echo $_product->getId(); ?>">
                                    <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                                         src="<?php echo $imageHelper->init($_product, 'category_page_list', ['height' => 80 , 'width'=> 80])->getUrl();?>"
                                         alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                                </a>
                            </div>
                            <div class="info-er-pu">
                                <p><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_product->getName(); ?>"><?php echo $_product->getName(); ?></a></p>
                                <?php echo $block->getProductPriceHtml($_product) ?>
                                <input type="hidden" name="rate" id='rate_<?php echo $_product->getId() ?>' value="<?php echo $block->taxRate($_product) ?>" readonly>
                                <div class="option-er-pu er-pu-<?php echo $_product->getId() ?>">
                                    <input type="hidden" name="productid" value="<?php echo $_product->getId() ?>">
                                    <?php echo $block->getProductOptionsHtml($_product,$configurable = true); ?>
                                </div>
                                <input type="hidden" name="fbt-product-select[]" class="fbt-product-select" id="fbt-product-select-<?php echo $_product->getId() ?>" value="<?php echo $_product->getId() ?>">
                                <div class="product-qty-er">
                                    <span><?php echo __('Qty'); ?></span>
                                    <input type="text" class="quantity" name="<?php echo $_product->getId() ?>_qty" id="qty-<?php echo $_product->getId() ?>" value="<?php echo $data['qty'] ?>">
                                </div>
                                <div style="display: none;" class="fixed-price-ad-pu">
                                    <span class="finalPrice"></span>
                                    <span class="basePrice"></span>
                                    <span class="oldPrice"></span>
                                </div>
                            </div>
                            <div class="remove-er-pu">
                                <span class="remove"></span>
                            </div>
                            <div style="clear: both"></div>
                        </div>
                    </div>
                    <?php $i++; endforeach; ?>
            </div>
            <div id="form_key_fbt"><input type="hidden" value="<?= $helper->getFormKey();?>" name="form_key"></div>
            <button type="submit" title="<?php echo __('Add all products to Cart') ?>" style="background: #<?php echo $helper->getPBackgroundBtn() ?>; border:1px solid #<?php echo $helper->getPBackgroundBtn() ?>;color: #<?php echo $helper->getPColorTextBtn();?>" class="action primary fbtaddtocartpopup" id="product-addtocart-button-er-fbt">
                <span><?php echo __('Add all products to Cart') ?></span>
            </button>
        </form>
    <?php endif ?>
    <?php if($helper->isPShowminicart()) :?>
        <div class="cart-info">
            <div class="items-count">
				<span>
					<?php echo ($cart['qty'] > 1) ? __('There are ') : __('There is '); ?>
					<a href="<?php echo $block->getUrl('checkout/cart'); ?>">
						<?php
                        echo $cart['qty'];
                        echo ($cart['qty'] > 1) ? __(' items') : __(' item');
                        ?>
					</a>
					<?php echo __(' in your cart.'); ?>
				</span>
            </div>
            <div class="subtotal">
				<span>
					<?php
                    echo __('Cart Subtotal: ');
                    echo $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($cart['subtotal'], true, false);
                    ?>
					<span data-bind="html: getCartParam('subtotal')"></span>
				</span>
            </div>
            <?php if($helper->isPShowminicheckout() && $cart['qty'] > 0) : ?>
                <div class="checkout-link">
                    <a href="<?php echo $block->getUrl('checkout')?>">
                        <span><?php echo __('Go to checkout'); ?></span>
                    </a>
                </div>
            <?php endif; ?>
        </div>
    <?php endif; ?>

    <div class="action clearfix" style="margin-top: 10px;">
        <div class="btn-viewcart <?php if(!$helper->isPShowContinueBtn()) { echo 'full-width'; }?>">
            <a href="<?php echo $block->getUrl('checkout/cart') ?>" title="<?php echo __('View Cart'); ?>" class="view-cart">
                <button class="viewcart" style="background: #<?php echo $helper->getPBackgroundBtnV() ?>; border:1px solid #<?php echo $helper->getPBackgroundBtnV() ?>;color: #<?php echo $helper->getPColorTextBtnV();?>" type="button" title="<?php echo __($helper->getPTextBtnV())?>">
                    <span><?php echo __($helper->getPTextBtnV()); ?></span>
                    <?php if($helper->getPActivecountdown() == '2') :?>
                        <span class="<?php echo ($helper->getPActivecountdown() == '2') ? 'countdown' : ''; ?>">(<?php echo $helper->getPCountdowntime(); ?>)</span>
                    <?php endif; ?>
                </button>
            </a>
        </div>

        <?php if($helper->isPShowContinueBtn()) : ?>
            <div class="btn-continue">
                <button class="continue" style="background: #<?php echo $helper->getPBackgroundBtnC() ?>; border:1px solid #<?php echo $helper->getPBackgroundBtnC() ?>;color: #<?php echo $helper->getPColorTextBtnC();?>" type="button" title="<?php echo __($helper->getPTextBtnC())?>">
                    <span><?php echo __($helper->getPTextBtnC()); ?></span>
                    <?php if($helper->getPActivecountdown() == '1') :?>
                        <span class="<?php echo ($helper->getPActivecountdown() == '1') ? 'countdown' : ''; ?>">(<?php echo $helper->getPCountdowntime(); ?>)</span>
                    <?php endif; ?>
                </button>
            </div>
        <?php endif; ?>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "#bss_fbt_cart_popup": {
            "Bss_FBT/js/popup": {
                "items": <?php echo $helper->getPItemslide() ?>,
                "slideSpeed": <?php echo $helper->getPSpeedslide() ?>,
                "autoPlay": <?php echo $helper->isPAutoslide()? "true" : "false"; ?>,
                "countDown": <?php echo $helper->getPCountdowntime(); ?>
            }
        }
    }
</script>
